import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import { Roboto } from 'next/font/google'
import { UrqlProvider } from '@/providers/urql'

import '@/styles/globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <UrqlProvider>
          <main>{children}</main>
          <Toaster position="bottom-center" mobileOffset={{ bottom: '25px', left: '10px' }} />
        </UrqlProvider>
      </body>
    </html>
  )
}
