query Orders(
  $status: [OrderStatus!]
  # pagination
  $first: Int!
  $after: String
  $before: String
) {
  orders(first: $first, after: $after, before: $before, where: { status: $status }) {
    pageInfo {
      hasNextPage
      startCursor
      endCursor
      hasPreviousPage
    }
    totalCount
    edges {
      cursor
      node {
        id
        price
        cityName
        status
        createdAt
      }
    }
  }
}
