query Products(
  $category: [CategoryType!]
  $gender: [Gender!]
  $tag: ProductTag
  $instock: Boolean
  $price: PriceRange
  $isHidden: Boolean = false
  $sortBy: ProductFilterSortBy
  # pagination
  $first: Int!
  $after: String
  $before: String
) {
  products(
    first: $first
    after: $after
    before: $before
    where: {
      category: $category
      gender: $gender
      tag: $tag
      instock: $instock
      isHidden: $isHidden
      price: $price
      sortBy: $sortBy
    }
  ) {
    totalCount
    priceRange {
      gt
      lt
    }
    pageInfo {
      hasNextPage
      startCursor
      endCursor
      hasPreviousPage
    }
    edges {
      node {
        id
        title
        inStock
        currentPrice
        basePrice
        tag
        preview
      }
    }
  }
}
