query GetProduct($id: ID!, $size: String) {
  product(id: $id, size: $size) {
    __typename
    ... on Product {
      id
      parentId
      title
      sku
      gender
      currentPrice
      basePrice
      amount
      tag
      preview
      category
      inStock
      description
      colorName
      sizeName
      brandName
      images
      isHidden
      defaultSizeID
      availableSizes
      updatedAt
      createdAt
      # availableColors {
      #   id
      #   title
      #   color
      # }
    }
    ... on NotFound {
      message
    }
  }
}
