query GetProduct($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      parentId
      title
      sku
      gender
      currentPrice
      basePrice
      amount
      tag
      preview
      category
      inStock
      description
      colorName
      sizeName
      brandName
      images
      isHidden
      defaultSizeID
      updatedAt
      createdAt
      availableColors {
        id
        title
        color
      }
    }
    ... on NotFound {
      message
    }
  }
}
