query Products(
  $gender: [Gender!]
  $instock: Boolean
  $tag: ProductTag
  $price: PriceRange
  $category: [CategoryType!]
  $page: Int!
) {
  products(
    filter: {
      gender: $gender
      isHidden: false # todo: make it optional
      instock: $instock
      tag: $tag
      price: $price
      category: $category
      page: $page
    }
  ) {
    priceRange {
      gt
      lt
    }
    pagination {
      totalPages
      currentPage
    }
    products {
      id
      slug
      title
      inStock
      currentPrice
      basePrice
      tag
      preview
    }
  }
}
