query GetProduct($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      sku
      gender
      currentPrice
      basePrice
      amount
      tag
      preview
      category
      inStock
      colorName
      sizeName
      brandName
      images
      isHidden
      updatedAt
      createdAt
      details {
        description
        dimensions
        weight
        capacity
      }
      availableSizes {
        size
        productId
      }
    }
    ... on NotFound {
      message
    }
  }
}
