query UserOrders($userId: ID!) {
  userOrders(userId: $userId) {
    id
    status
    price
    receiverName
    receiverSurname
    receiverPhone
    supplier
    cityName
    postOfficeName
    parcelTrackId
    updatedAt
    createdAt
  }
}
