import Head from 'next/head'
// import Modal from 'react-modal'
import client from '../apollo/client'
// import { AppLayout } from '@/components/AppLayout'
import { ApolloProvider } from '@apollo/client'
// import { ThemeProvider } from '@/providers/theme'
import { Montserrat } from 'next/font/google'
import { appWithTranslation } from 'next-i18next'
import nextI18NextConfig from '../../next-i18next.config'
import type { AppProps } from 'next/app'

// import '../../node_modules/modern-normalize/modern-normalize.css'
import '@/styles/globals.scss'

type AppPropsWithLayout = AppProps

const montserrat = Montserrat({
  weight: ['400', '500', '600'],
  subsets: ['latin', 'cyrillic'],
  style: 'normal',
  variable: '--font-montserrat',
  display: 'swap'
})

// Modal.setAppElement('#__next')

const MyApp = ({ Component, pageProps }: AppPropsWithLayout) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client}>
        {/* <ThemeProvider> */}
        {/* <AppLayout> */}
        <style jsx global>
          {`
            html {
              font-family: ${montserrat.style.fontFamily};
            }
          `}
        </style>
        <Component {...pageProps} />
        {/* </AppLayout> */}
        {/* </ThemeProvider> */}
      </ApolloProvider>
    </>
  )
}

// INFO: https://github.com/i18next/next-i18next/issues/1917
export default appWithTranslation(MyApp, nextI18NextConfig)
// export default MyApp
