query OrderByID($id: ID!) {
  order(id: $id) {
    __typename
    ... on Order {
      id
      price
      receiverName
      receiverSurname
      receiverPhone
      cityName
      postOfficeName
      parcelTrackId
      status
      supplier
      paymentMethod
      updatedAt
      createdAt
      products {
        id
        quantity
        priceAtOrder
        product {
          id
          title
          preview
          category
        }
      }
    }
    ... on NotFound {
      message
    }
  }
}
